channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==1.26.2
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.11.4
name: mlflow-env
